'use client';
import React, { useEffect, useState } from 'react';
import { FileText, Download, Plus, Printer, Shield } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import jsPDF from 'jspdf';

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);

  useEffect(() => {
    fetch('/api/reports')
      .then((r) => r.json())
      .then((d) => Array.isArray(d) && setReports(d))
      .catch(() => {});
  }, []);

  const downloadPdf = (report: any) => {
    const doc = new jsPDF();
    doc.setFont('courier', 'bold');
    doc.setFontSize(16);
    doc.text('SUMI-TAH THREAT HUNTING PLATFORM', 20, 20);
    doc.setFontSize(12);
    doc.setFont('courier', 'normal');
    doc.text(`REPORT: ${report.title}`, 20, 30);
    doc.text(`TYPE: ${report.type}`, 20, 38);
    doc.text(`AUTHOR: ${report.authorName}`, 20, 46);
    doc.text(`DATE: ${new Date(report.createdAt).toLocaleString()}`, 20, 54);
    doc.line(20, 58, 190, 58);
    doc.text('EXECUTIVE SUMMARY:', 20, 68);
    doc.setFontSize(10);
    const splitSummary = doc.splitTextToSize(report.summary, 170);
    doc.text(splitSummary, 20, 76);
    doc.save(`${report.title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-charcoal-800">
        <div>
          <h1 className="text-2xl font-bold text-gray-100 flex items-center space-x-3">
            <FileText className="w-6 h-6 text-jade-400" />
            <span>Investigation & Threat Intelligence Reports</span>
          </h1>
          <p className="text-xs text-gray-400 font-mono mt-1">
            Persisted investigation reports with executive summaries and PDF generation.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reports.map((rep) => (
          <Card key={rep.id} className="flex flex-col justify-between">
            <CardHeader>
              <div className="flex items-center justify-between mb-2">
                <Badge variant="jade">{rep.type}</Badge>
                <span className="text-[10px] font-mono text-gray-400">{new Date(rep.createdAt).toLocaleDateString()}</span>
              </div>
              <CardTitle className="text-base">{rep.title}</CardTitle>
              <CardDescription className="mt-1">{rep.summary}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 pt-0">
              <div className="text-xs text-gray-400 font-mono">
                Generated by: <strong className="text-gray-200">{rep.authorName}</strong>
              </div>
              <div className="flex justify-end pt-2 border-t border-charcoal-800">
                <Button size="sm" variant="primary" onClick={() => downloadPdf(rep)}>
                  <Download className="w-3.5 h-3.5 mr-1.5" />
                  Download PDF Report
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}